version: '3.7'

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    stdin_open: true  
    command: npm start  
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
