export const projectResponsibility = [
  'System architecture design',
  'Database design',
  'Refactoring legacy code',
  'Code cross review',
  'Front-End development',
  'Back-End development',
  'Unit tests coverage',
  'Code review',
  'API development and bug fixing',
  'CI/CD and Cloud Infrastructure setup',
  'Reverse engineering',
  'Set up CI for application',
  'Mobile application development',
  'Estimation of development activities',
  'Solution design',
  'Mentoring of the development team',
  'Functional, usability, UI testing of Web and Mobile applications',
  'Participation in meetings with Product Owner and other parts of the team',
  'Requirements analysis',
  'Testing documentation (test cases, checklists, test plans) composing',
  'Regression testing',
  'Daily based reporting on the testing process.',
  'Bug reports/improvement tickets creating and monitoring',
  'Estimation of testing activities',
  'User feedback analysis, and following user case examination',
  "Creating a repository of knowledge for the project, with a set of up-to-date articles on the project's core functionality.",
  'Manual and automation testing of server-side',
  'Making demo presentations to Product Owner and stakeholders',
  'Load and performance testing',
  'Security testing and vulnerability scanning',
  'Create and maintain automation test scripts',
  'Business analysis and requirements preparing',
  'Managing change requests processing',
  'Managing risks associated with requirements changes',
  'Prototypes and mockups creation',
  'Analysis of business and functional requirements and/or use cases for websites and web services, mobile applications',
  'Leading and managing project teams - developers, QA, BA, stakeholders',
  'Development and execution of resource and project plans - staff the project teams accordingly and track the progress of tasks and sprints',
  'Organization of development process, daily control of development process, monitoring of team performance, keeping it highly motivated',
  'Managing projects scopes and change requests, risks associated with requirements changes',
  'Coordinating and leading project team meetings',
  'Communication with stakeholders on the progress and risks, suggesting tentative solutions',
  'Working with Tech Leads to determine the right technical solutions that meet specific business requirements',
  "Handle Scrum's essential activities, such as sprint, sprint planning, daily Scrum, sprint review, and sprint retrospective",
  'Reporting on the project progress, timely informing about any project changes',
  'Tailor different approaches and project management frameworks',
  'Creation of new development processes and improvement of existing using evolutionary changes',
  "Coordination between distributed teams (client's inhouse team and nix team)",
  'Keep the publishing of the applications according to schedule',
  'Team keeping activities (onboarding etc.)',
  'Reporting according to the team roster',
  "Interview and mentor project managers and other experts on the client's side",
  'Close cooperation with the stakeholders, backlog refinement, grooming sessions and other Scrum activities',
  'Managing Jira product backlog',
  'Control the project milestones',
  'Tracking of the team progress',
  'Maintain the team motivation',
  'Weekly reports with the status update',
  'Dashboards and reports creation',
  'Data analysis',
];
