export const techStackOptions = {
  'TECHNICAL EXPERTISE': [
    'Take an active part in all aspects of the development lifecycle.',
    'Aimed to produce scalable, secure, and fast code.',
    'Experienced in project estimation, providing suggestions and improvements.',
    'Keen to deliver high-quality code within accepted project limitations.',
    'Take responsibility for the most challenging areas of work.',
    'Mastership in software engineering using best practices: object-oriented design, refactoring, design patterns, continuous integration, unit testing, and TDD.',
    'Comprehensive experience in carrying estimation and application architecture, project planning, and identification of risks.',
    'Solid experience of choosing the most applicable solutions taking into account all business needs.',
    'Proven ability to take an active role in all stages of software development: planning, estimations.',
    'Great abilities to analyze and resolve complex problems.',
    'Solid understanding of software lifecycle and adherence to clean code standards and best development practices.',
    'Wide experience in web applications unit-testing, REST services.',
    'Strong adherence to clean code standards and best development practices.',
    'Solid understanding of various data types, data structures as well as algorithms.',
    'Comprehensive background in building high-performance applications.',
    'Aimed to produce scalable, secure, and fast code.',
    'Flexibility to adapt new technologies into current projects and stabilizing its features.',
    'Expert in the full system development life cycle with in-depth knowledge of OOP.',
    'Strong adherence in developing effective solutions with high modularization, as well as addressing all business needs a functional perspective.',
    'Skilled in software engineering using best practices: object-oriented design, refactoring, design patterns, continuous integration, unit testing, and TDD.',
    'Comprehensive experience in carrying estimation and application architecture, project planning and identification of risks.',
    'Solid experience of choosing the most applicable solutions taking into account all business needs.',
    'Experienced in establishing a QA environment from scratch on a brand-new project.',
    'Got experience in working on several small projects simultaneously, distributing time and team resources.',
    'Solid experience working in agile teams and good knowledge of Agile methodology and principles.',
    'Broad experience working in agile teams and good knowledge of Agile methodology and principles, including Scrum.',
    'Able to the setup a process for the QA team from scratch',
    'Wide experience in application deployment and source code management following the best practices.',
    'Proven ability to mentor junior-level team members.',
    'Solid understanding of cloud application deploys and delivery processes.',
    'Comprehensive experience in cloud development. Solid expertise in working with large-scale data processing.',
    'Comprehensive background in building high-performance applications.',
    'Experienced in setup and maintenance of CI/CD tools.',
    'Proven ability to lead the agile team, daily review the development process, follow agile best practices.',
    'Wide experience in CI/CD and Cloud Infrastructure setup.',
  ],
  COMMUNICATION: [
    'Excellent English level with advanced communication skills.',
    'Have experience working with remote teams distributed worldwide.',
    'Ability to carry on communication on all levels of the development process. Conduct technical and business meetings and sessions. Lead the process and facilitate the team.',
    'Quick learner and result-oriented person.',
    'Advanced English level.',
    'Excellent communication skills with the ability to effectively interact with product owners, business analysts, engineering managers, development teams, upper management, and other groups in a cross-functional team.',
    'Experienced in conducting technical and business meetings and sessions. Lead the process and facilitate the team.',
    'Experience of efficient interaction with other tech teams, knowledge sharing.',
    'Great communication skills with an excellent English level.',
    'Have experience working with remote teams distributed worldwide.',
    'Experienced in communication with both the stakeholders and the execution team.',
    'The vast experience of direct communication with clients and tech teams.',
    'Vast expertise in interacting with product owners, architects, developers, QA engineers, and other members of a team.',
    'Solid experience working with worldwide distributed teams according to Agile methodologies.',
    'Excellent communication skills with the ability to collaborate and build a strong relationship with product owners, developers, QA engineers, and other experts.',
    'Comfortable in following Agile routines, broad experience in interacting with product owners, business analysts, engineering managers, development teams, upper management.',
    'Productive team member with great abilities to collaborate with other developers, product owners, and scrum masters.',
    'Excellent communication skills with the ability to effectively interact with product owners, business analysts, engineering managers, development teams, upper management, and other groups in a cross-functional team.',
    'Solid experience in effective collaboration with product managers, architects, QA, and DEV teams in cross-functional, geographically distributed teams to ensure the highest quality product.',
    'Proven ability to conduct technical discussion, highlight risks, identify problems, and propose solutions during the project lifecycle.',
    'Skilled to highlight potential bottlenecks, being extremely attentive to details.',
    'Proven ability to identify issues and escalate potential problems to management along with suggestions.',
    'Obtained skills in arranging and conducting meetings and telecommunications sessions with tech teams and stakeholders.',
    'Wide experience in setup and leading business meetings.',
    'Attention to detail and an ability to identify issues and escalate potential problems with the suggested solutions to management.',
    'Expertise in exchanging information with other technical experts and managers, share results, provide suggestions outside the project area.',
    'Ability to carry on communication on all levels of the development process. Conduct technical and business meetings and sessions. Lead the process and facilitate the team.',
    'Experienced in conducting technical and business meetings and sessions. Lead the process and facilitate the team.',
    'Eagerly integrates best practices in the development process, keeps an informed eye on leading technology, tools and approaches.',
    'Quick learner and result-oriented person.',
    'Good team player and highly responsible person.',
    'Flexible thinking and problem-solving.',
    'Quick-learner and with a good eye for detail.',
    'Experience of efficient interaction with other tech teams, knowledge sharing.',
    'The proactive, responsible, result-oriented person, efficient both as a team player and independently.',
    'Attentive to details, with strong analytical skills.',
    'Great team-player, expertise in exchanging information with other developers and managers, share results, provide suggestions.',
    'Team player having exceptional organizational, problem-solving, and communication skills.',
  ],
  LEADERSHIP: [
    'Experience in creating training programs; took part in interviews and performance reviews.',
    'Carried out mentoring and training of less experienced team members, initiated knowledge sharing activities and solutions reviews.',
    'High skilled in mentoring and consulting team members, interaction with Project Management and other development teams to ensure progress and coordination.',
    'Managed mentoring and code review of less experienced team members.',
    'Substantial experience in reviewing the solutions of other technical-leads and experts, approve the changes in architecture, give recommendations to apply alternative solutions and approaches.',
    'Solid experience in reviewing the solutions of other technical-leads and experts.',
    'Carried out a code review of other team members and mentoring, initiated knowledge sharing activities and solutions reviews.',
    'Takes ownership of the most critical project solutions.',
    'Keen on complex tasks implementation.',
    'Strong skills to make decisions quickly with the available information.',
    'Proven ability to take ownership of the most critical parts of the project.',
    'Flexible to adapt to leading-age technologies and chose the best of them to meet project needs.',
    'Ability to provide an efficient knowledge transfer to newly added developers in the project.',
    'Ability to come up with alternative solutions and approaches.',
    'Take responsibility for the most challenging areas of work.',
    'Proven ability to lead the team, daily control development process, monitor team performance without any need in supervision.',
    'Capable of being a dependable leader and creating a resilient team that is able to work through difficulties that may arise.',
  ],
};
